apiVersion: v1
kind: Service
metadata:
  name: leave-api-service
spec:
  selector:
    app: leave-api
  ports:
    - protocol: TCP
      port: 80 # The port we hit from the outside
      targetPort: 8000 # The port the container listens on
  type: LoadBalancer # Gives us a URL to access the app
